### ISSUE TITLE
duplicate centrifuges

### ISSUE THREAD

**Issue by OsamaBinWOG** [Pezzawinkle/MadClowns#10]
It looks like bob's now has a centrifuge 2, and 3, which show up in addition to the madclowns centrifuge mk1, 2, and 3

The bob's ones still have older style recipes and faster crafting speed

**Comment by Pezzawinkle** [comment]
Im pretty sure i have a setting for this already, my clowns versions are perfectly serviceable with just angels, and some people wanted to have the flexibility even with bobs, so i left them as a setting and not an auto-disable.

**Comment by OsamaBinWOG** [comment]
I guess I didn't look through the setting well enough, you have a setting to disable your mk2 and 3, and bob's also has a setting to disable his 2 and 3.

I was assuming it would work like the other angel's stuff where it just removes his stuff no matter what the setting on bob's
