### ISSUE TITLE
incompatibility with IR2

### ISSUE THREAD

**Issue by the-clorax** [Pezzawinkle/MadClowns#11]
vanilla nuclear does not let IR2 load when IR2 is present. this mod would fill in IR2's void of nuclear technology very well if they were compatible. also some changes to the recipes when IR2 is present would be nice, such as the reprocessing recipes and the atomic bomb recipe making IR2's artillery shell that replaces the vanilla atomic bomb.

**Comment by Pezzawinkle** [comment]
I dont currently support that mod with any of the angels family of mods, but id be happy to take a look at it.

**Comment by Pezzawinkle** [comment]
well, that was quicker than I thought :D
I had not removed the fuel cell from the tech that it unlocks in for vanilla, while the recipe to make it comes from the recipe after it, causing the error in IR2.
Ill put an update out immediately if you could please give me some feedback.

**Comment by the-clorax** [comment]
the recipe for nuclear fuel cells and atomic bombs become odd. normally IR2 adds an atomic artillery shell and removes vanilla nuclear weapons. the centrifuiging recipes don't appear to be anywhere. IR2's recipes seem to override this mod's.

**Comment by Pezzawinkle** [comment]
in that case, ill need to re-work that, possibly stick the recipes into a different entity if the centrifuge is gone

**Comment by the-clorax** [comment]
the centrifuge is there, i am not sure why the recipe was removed. is it possible to change this in a data-final-fixes file to avoid IR2's messing with the recipes?

**Comment by Pezzawinkle** [comment]
OK, that took a but to get working... I had some library functions in the AB version which I migrated across, it needed some work to get working properly, but I'm happy with the way it works now...

**Comment by the-clorax** [comment]
below is a list of issues, which is a lot to fix, but i can help if you would be interested. this is a mod that really completes IR2, but they seem like they will be hard to make an integration for. i am new to modding but i could try making a mod file that has integration with IR2 and sending it to you. otherwise i can make an integration mod.

 i think it would most work if nuclear bombs were replaced with artillery shells, the artillery shells were changed to use 30 HEU or 20 Pu-239 in addition to 20 lead-plate and 1 artillery-shell and thermonuclear bombs to involve field effectors, electromagnetic coils, and a computer-mk3 because IR2 tries to remove nuclear weapons altogether in favor of nuclear in the bombs recipes file

something is changing the default fuel cell recipe that needs 10 lead-plate-special, 1 u-235, and 19 u-238. now it takes 1 35%-uranium, 1 u-238, and 1 shielded steel plate. 

MOX fuels could use lead-plate-special to fit IR2 better

IR2 fuel rods are reprocessed one at a time, this mod brings it up to 5

something got rid of the advanced centrifuging recipe

**Comment by Pezzawinkle** [comment]
> something is changing the default fuel cell recipe that needs 10 lead-plate-special, 1 u-235, and 19 u-238. now it takes 1 35%-uranium, 1 u-238, and 1 shielded steel plate.

the 35% uranium is from my mod, the 1 U-235 is also I think my change, and it should only be making 1, but I can fix that. My mod also removes Kovarex as it is irrelevant with the enrichment profile it adds.

**Comment by Pezzawinkle** [comment]
> i think it would most work if nuclear bombs were replaced with artillery shells, the artillery shells were changed to use 30 HEU or 20 Pu-239 in addition to 20 lead-plate and 1 artillery-shell and thermonuclear bombs to involve field effectors, electromagnetic coils, and a computer-mk3 because IR2 tries to remove nuclear weapons altogether in favor of nuclear in the bombs recipes file

I will NOT be removing the nuclear warheads, but i don't have an issue looking at creating "themed recipes" for the artillery shells, especially since plutonium is far more useful as a nuclear weapons material than uranium.

>> I did notice that the mod does include "artillery" weapons which use the regular nuclear weapons as ingredients (its a setting, ill force that on if this mod is active, if you want can come up with some alternative recipes...

>something is changing the default fuel cell recipe that needs 10 lead-plate-special, 1 u-235, and 19 u-238. now it takes 1 35%-uranium, 1 u-238, and 1 shielded steel plate.

 This is intended, but I can swap it to lead plate from the plate...
 Just to clarify... the default recipe is:
 `19 U-238 + 1 U-235 + 20 lead-plate-special --> 10 uranium-fuel-cell`
 Clowns default version is:
 `20 U-238 + 20 35%-U + 20 iron-plate --> 10 uranium-fuel-cell`
 
 > something removed the advanced centrifuging recipe
 
 Kovarex? Very intentional, the enrichment method clowns adds is very different.
 
 > IR2 fuel rods are reprocessed one at a time, this mod brings it up to 5
 
 The fuel cell reprocessing IR default recipe is:
 `1 cell --> 1-2 U-238 + 0.2 lead-scrap + 0.5 carbon-steel-scrap`
 Clowns default is:
 `5 cell --> 3 U-238 + 3 Pu-239`

**Comment by Pezzawinkle** [comment]
on the point of the re-processing, i don't mind changing it back to 1, but ill need to tweak some of the results down a bit

**Comment by Pezzawinkle** [comment]
I have made a substantial change to the systems, it should work much better now.
Ill work up some draft recipes for the nuclear artillery (that are a bit more substantial than they currently are), but i don't have the right now, actually debugged a few issues with the function lib i has available to this mod :(
Better fixed now that realise how broken things are when i start using them for the other mods (mainly science)

**Comment by Pezzawinkle** [comment]
@the-clorax can test the current dev version, and draft some recipes for the artillery shells (they do already exist)
