### ISSUE TITLE
Crash in startup

### ISSUE THREAD

**Issue by SilverScreamBr** [Pezzawinkle/MadClowns#12]
Failed to load mod "Clowns-Processing": __Clowns-Processing__/prototypes/items/vanilla-items.lua:399: attempt to index field 'pictures' (a nil value)
stack traceback:
	__Clowns-Processing__/prototypes/items/vanilla-items.lua:399: in main chunk
	[C]: in function 'require'
	__Clowns-Processing__/data.lua:24: in main chunk

**Comment by Pezzawinkle** [comment]
Sorry I missed this, ill look at it tonight, do you have a mod list I cam start digging with?

**Comment by Pezzawinkle** [comment]
I think I have a fix in dev, but I need confirmation before I publish it to the mod portal.
I have a few other changes I want to finalise before I get the next version out, so this may not be "quick".

**Comment by SilverScreamBr** [comment]
https://mods.factorio.com/mod/AngelBobPyanadonPack/downloads

**Comment by Pezzawinkle** [comment]
well, considering the shenanigans going on with that pack, im not surprised my icon update functions were failing... ill have a patch up in the next few days.

**Comment by Pezzawinkle** [comment]
I have patched my side of things, im getting a well known Py ingredient duplication error on start-up now... if you use the version of science from here you will see what i mean
