### ISSUE TITLE
Error loading v1.3.14

### ISSUE THREAD

**Issue by Curry** [Pezzawinkle/MadClowns#14]
Loading Madclowns Nuclear v1.3.14 gives me this error
![image](https://user-images.githubusercontent.com/3466488/121899165-c5a05f00-cce9-11eb-9397-ac5bf35c26d1.png)

Mod list:
https://hatebin.com/cbbeyrksnc

**Comment by Pezzawinkle** [comment]
my bad, ill get that patched ASAP
