### ISSUE TITLE
an error appears

### ISSUE THREAD

**Issue by sampistola** [Pezzawinkle/MadClowns#16]
the error appears in data.lua: 16 with something from the table and it does not allow play, you can repair it please and make it soon since I will not be there to play it for a limited time

the mod is on Clowns Extended Minerals

**Comment by Pezzawinkle** [comment]
Can you please be more specific? at least an image of the error message would help

**Comment by sampistola** [comment]
I'm sorry if I didn't put an image I'm not good with those details but at least I put the bug although I don't know if you could repair it I hope that if I wanted to put that mod since it is almost essential I think but now I need other mods that are not there on this page to be sure that I have fun playing I like the fun that factor generates factorio the theme of the game looks a bit like real life I hope you have already fixed the bug

**Comment by sampistola** [comment]
This is what came out now, I don't know what makes it fail

![esto es lo que me sale](https://user-images.githubusercontent.com/6127571/128547255-8df0846b-0cba-4fa5-9fa1-0ea10e4802a3.png)

**Comment by sampistola** [comment]
and that there are only 315 factorio mods plus that of the problem and I have removed several to reduce so that it is not damaged but it is still damaged infrequently

**Comment by sampistola** [comment]
.... I will try if I put it right and I will notify you if it is with the failure

**Comment by sampistola** [comment]
I put everything that was there and it got worse I hope you repair the mods that appear in the image that I put please and thank you

**Comment by Pezzawinkle** [comment]
Ah, as I suspected, the issue came from when I moved the declaration to processing.
This error does not appear if you are running with clowns processing version 1.3.15 (latest portal version).
I may have forgotten to update the pre-req lower limit for clowns on the last release.
I'm just putting some finishing touches on an angels release, ill make sure this is fixed for the next release.

**Comment by sampistola** [comment]
ok I'll be waiting for him, I'll wait, I'm patient

**Comment by Pezzawinkle** [comment]
in the meantime, can you check that you are running both of the latest portal versions of processing and extended-minerals.

**Comment by sampistola** [comment]
I can't download mods because I'm not affiliated and I just have to wait here on the page to be able to use the mod
