### ISSUE TITLE
Possible Error with some recipes.

### ISSUE THREAD

**Issue by shadoworld56** [Pezzawinkle/MadClowns#17]
Not sure if this is a Madclown issue or an Angel issue but the following recipes seem to fail to produce anything. I have a pretty extensive mod list so it may be my end. Any idea what these should be making?

<details>
<summary>
Images
</summary>

![image](https://user-images.githubusercontent.com/2913908/126896705-82571823-aa2a-4909-bbca-ce49aabebc8c.png)

![image](https://user-images.githubusercontent.com/2913908/126896826-c3314e41-ce7a-4087-aab3-4197ff824030.png)

![image](https://user-images.githubusercontent.com/2913908/126896830-9e52c2c2-fcb1-4bc6-855c-c791c77ff2b0.png)

![image](https://user-images.githubusercontent.com/2913908/126896836-ac1c3e58-61b2-440a-9b74-b7c7ebe47f45.png)

![image](https://user-images.githubusercontent.com/2913908/126896846-a85cdb66-bbae-4b0f-8c62-6cc09cb0d112.png)

![image](https://user-images.githubusercontent.com/2913908/126896853-b4e99d28-87f8-49fd-8279-6bd0debc3482.png)

![image](https://user-images.githubusercontent.com/2913908/126896861-cdeba2c4-eae8-4ba3-9c93-c669f66660b7.png)

</details>

**Comment by Pezzawinkle** [comment]
1) phosphorus (from clowns processing) -- im not sure why this would fail
2) nexelit (pyanodon) --should be hidden if not active
3) niobium (pyanodon) --should be hidden if not active
4) rare-earth-dust (pyanodon) --should be hidden if not active
5) molybdenum (pyanodon) --should be hidden if not active
6) regolites (pyanodon) --should be hidden if not active
7) kimberlite (pyanodon) --should be hidden if not active

so if those are showing (researched etc), but don't have the results, can you flick me a dummy save so i can debug the issue for you. If they are disabled (i.e. only visible in editor/creative) then that is fine.
