### ISSUE TITLE
Angels mod update

### ISSUE THREAD

**Issue by domis86** [Pezzawinkle/MadClowns#18]
There was big update in Angels mods: https://github.com/Arch666Angel/mods/pull/659

TLDR: cobalt and gold was moved to "crystals" tier. Silver was moved to "chunks" tier.

Probably ore sorting in MadClowns mod should be adjusted aswell?

For example now:
* cobalt ore can be produced by "elionagate chunks processing"
* silver ore "specialist sorting" require crystals instead of chunks

etc

**Comment by Pezzawinkle** [comment]
while I may agree with you on principle, most of the stuff in clowns is designed around a bit more flexibility, even to the point of allowing things to be accessed earlier.

**Comment by domis86** [comment]
@Pezzawinkle ok, but what about mentioned silver recipe? It now requires crystals tier - but should require chunks.

**Comment by Pezzawinkle** [comment]
ill review this over the next week hopefully

**Comment by Pezzawinkle** [comment]
I have swapped the pure recipes for cobalt and silver (positionally, while swapping the crotinnium to cobalt) in the new version, this should satisfy things. I do still want the cobalt to activate a little earlier if possible, so the single-in sorting recipes will keep cobalt at chunk levels.
