### ISSUE TITLE
Startup error, MadClown01's Extended AngelBob Minerals incompatible with Angel's Infinite Ores

### ISSUE THREAD

**Issue by sparr** [Pezzawinkle/MadClowns#20]
angelsinfiniteores 1.1.24
Clowns-Extended-Minerals 0.9.10
mod-list.json: `{"mods":[{"name":"base","enabled":true},{"name":"angelsinfiniteores","enabled":true},{"name":"angelspetrochem","enabled":true},{"name":"angelsrefining","enabled":true},{"name":"angelssmelting","enabled":true},{"name":"Clowns-Extended-Minerals","enabled":true},{"name":"Clowns-Processing","enabled":true}]}`

startup error:
```
Failed to load mod "Clowns-Extended-Minerals": __Clowns-Extended-Minerals__/data.lua:86: attempt to index field 'infinite-clowns-ore2' (a nil value)
stack traceback:
	__Clowns-Extended-Minerals__/data.lua:86: in main chunk```

**Comment by Pezzawinkle** [comment]
Sorry for the delay, this was an oversight with the special vanilla tweaks... ill get this out in the next release.
