### ISSUE TITLE
Science Incompatible with "Burner Power Phase" of Bob's Technology

### ISSUE THREAD

**Issue by the-red-lily** [Pezzawinkle/MadClowns#22]
Issue: No steam power science recipes are available for hand crafting at the beginning of the game, locking out the entire tech tree

To reproduce: Enable "Burner Power Phase"  option of Bob's Technology in Mod Settings during map creation

**Comment by the-red-lily** [comment]
For context, Burner Power Phase locks steam power behind the tech tree, so you start with only burner technology

**Comment by Pezzawinkle** [comment]
This is known, and I think i even stated it in the logs... the tech tree should be dealt with, but i don't think i remove bobs steam packs? I do need to look into this when im feeling a bit more energetic.

**Comment by Pezzawinkle** [comment]
this should be fixed with todays hotfix
