### ISSUE TITLE
Madclowns-AngelBob-Nuclear

### ISSUE THREAD

**Issue by Xman1109** [Pezzawinkle/MadClowns#23]
Hi,
I would like to suggest to upscale some icons like for example the polonium, zinc, or thorium to 64×64 pixels as that would improve the quality of the icons.
And I want to recommend making mipmaps for these icons, as that would improve the FPS when playing with a bigger modpack that adds lots of new items.

**Btw, your mods are great :D**

**Comment by Pezzawinkle** [comment]
![image](https://user-images.githubusercontent.com/54166225/170807560-c133aec4-b5e6-4665-b042-d8a9d0dab90c.png)
this is pretty much as good as i could get it given the short time i have... it does also have mipmaps... so hopefully this next update will help.

**Comment by Xman1109** [comment]
Perfect! :D
