### ISSUE TITLE
Cobalt Plate // Cobalt Steel Alloy recipe bug

### ISSUE THREAD

**Issue by djfariel** [Pezzawinkle/MadClowns#24]
https://github.com/Pezzawinkle/MadClowns/blob/0fcaf6c4add96fd938448f7ec3aa64ba6da53b8b/Clowns-Science/prototypes/buildings/particle-accelerator.lua#L6

Using the Multiplayer Extreme Modpack, it seems that `cobalt-plate` is disabled and recipes that use it instead use `cobalt-steel-alloy`. Mods that affect these recipes seem to be "Bob's Metals, Chemicals, and Intermediates" and "Angel's Smelting" if I'm reading the passthrough correctly. It seems there are three recipes in Madclown's Science that don't pick this up: Particle Accelerator Mk 1 (linked), Production Science Pack, and Utility Science Pack.  It seems to already be updated properly for Chemical Science Pack.

**Comment by Pezzawinkle** [comment]
This is due to an external mod which is likely part of the pack. That mod tries to fix an error i cannot even duplicate...
https://mods.factorio.com/mod/Dan-MadClown-Science-Cobalt
this is not one of my mods.
