### ISSUE TITLE
Error when loading AB Nuclear

### ISSUE THREAD

**Issue by yyj1996** [Pezzawinkle/MadClowns#26]
![image](https://user-images.githubusercontent.com/25203466/167256158-19a10967-bf4f-4bd2-9cec-2939feafddae.png)

**Comment by yyj1996** [comment]
I found this bug will occur if I load clowns-AB-nuclear with bobplates (MCI) together, where the latter is required by clowns-extended-minerals.

**Comment by Pezzawinkle** [comment]
Sorry, i am pretty sure i fixed this in the last version, ill test this further
