### ISSUE TITLE
MadClown Ore Chunk Recipe Incorrect

### ISSUE THREAD

**Issue by Mr-Wacko** [Pezzawinkle/MadClowns#28]
The recipes for all MadClown ore chunks require one too few ore chunks, compared to standard AngelBob ores. See attached images compared to standard AngelBob ores.

I suspect changing the amount in the line below will fix the issue: https://github.com/Pezzawinkle/MadClowns/blob/44db541a6a187cca5a71a0ac820b825f47e91207/Clowns-Extended-Minerals/prototypes/recipes/ore-sorting.lua#L273
![image](https://user-images.githubusercontent.com/16530192/209884283-6e14b051-d745-450a-8ad1-4d35c297ac32.png)
![image](https://user-images.githubusercontent.com/16530192/209884309-417b54a4-ba1b-4dfb-bf4f-94ecfa93bf31.png)

**Comment by Pezzawinkle** [comment]
you are indeed correct, that should be a 6.

**Comment by Pezzawinkle** [comment]
ill do a batch of fixes and hopefully have this on the portal soon
