### ISSUE TITLE
Please fix the bugs since BOb's mod with ANGEL's Mod in the updated version of January 1, 2023.

### ISSUE THREAD

**Issue by Andy91320** [Pezzawinkle/MadClowns#29]
Hello，MadClown01：
    Currently, I have confirmed the following bugs.
1. The first step of the thorium processing process: thorium salt solution, fails because the manufacturing building cannot be found.
2. The cobalt plate used to research the yellow (science) research kit has no manufacturing process, probably disposed of by angel mod as useless parts. The cobalt plate is now the version provided by angel mod, but is not available.
3. The manufacture of TNT (tertiary explosives) can not find the corresponding building. Just like the manufacture of nitroglycerin can not find the corresponding building. Previously, they can be manufactured from the Advanced Chemical Factory II.
4. These bugs were created after the major update of angel's mod and BOB's mod on Jan 1, 2023, please refer to their changelogs for details.

**Comment by Andy91320** [comment]
update, Q3 was fixed by Angel's~2023.02.25

**Comment by Pezzawinkle** [comment]
Sorry this took soo long, been crazy busy IRL, will look at this today

**Comment by Pezzawinkle** [comment]
I have a fix for the first one, thanks for bringing that up.
I cannot for the life of me find the issue with cobalt plates in my testing, but i will keep looking

**Comment by Andy91320** [comment]
Hello Pezzawinkle，I just downloaded your update for 《MadClown01's Science》 ，but the frist bug is not fixed. I think the frist bug is should belong to one of 《MadClown01's Nuclear Extension》，《MadClown01's AngelBob Nuclear Extension》，《MadClown01's Extended AngelBob Minerals》 or《MadClown01's Processing》. Please have time to check it out.
About Bug 2, I found a mod is《MadClown01's Science - No cobalt plates》，and it worked. This mod page : https://mods.factorio.com/mod/Dan-MadClown-Science-Cobalt . Thank for your work ,it's make me very enjoy it.

**Comment by Pezzawinkle** [comment]
After having another dig, I did find that I was not forcing the cobalt plate to be enabled under all valid conditions, this should be fixed in the next version (hopefully today). The fixes for the nuclear recipes will be uploaded today, sorry for the delay.
