### ISSUE TITLE
MadClown's Science recipes are unlocked at the start of the game

### ISSUE THREAD

**Issue by adoa** [Pezzawinkle/MadClowns#30]
![Bildschirmfoto vom 2023-04-14 18-41-00](https://user-images.githubusercontent.com/1843557/232107104-a964af60-912d-4f4e-b20a-19480342cd5c.png)

All of MadClown's Science recipes are unlocked at the start of the game. This is clearly not intended.

Angel+Bob+Madclown (no additional overhauls)
MadClown's Science 1.1.2

**Comment by Pezzawinkle** [comment]
This should now be fixed in 1.1.3
