### ISSUE TITLE
Error loading sprite with Clown Processing 1.3.18

### ISSUE THREAD

**Issue by momosundeass** [Pezzawinkle/MadClowns#31]
Only setting that changed from default
![image](https://user-images.githubusercontent.com/8778954/232313479-bc7eb027-a6a4-4d2b-9b2e-429031b118da.png)

Here is error message
![image](https://user-images.githubusercontent.com/8778954/232313582-4ad1fb36-08b6-4f24-aa98-df544aa69d0e.png)

**Comment by Vascar** [comment]
I had the same error but I found a fix for it. In the mod file navigate to "Clowns-Processing_1.3.18.zip\Clowns-Processing_1.3.18\graphics\icons\", I used 7-zip to do this, and rename the folder named "Numbers" to "numbers".

**Comment by Pezzawinkle** [comment]
Apologise, I did fix this one as soon as I could
