### ISSUE TITLE
Platinum processing not in tech tree

### ISSUE THREAD

**Issue by Roukedou** [Pezzawinkle/MadClowns#32]
I just updated both "Extended AngelBob Minerals" and "Processing". Since then, platinum wire is required in CPU's, but platinum processing does not show up in the tech tree. I also have "ScienceCostTweaker Mod (mexmer)", but this only appeared after the update.

**Comment by Pezzawinkle** [comment]
Interesting, this must have been a change I made a while ago without realising, I'll investigate and patch this in the coming days

**Comment by stetown** [comment]
. is there anything happening with this as i am stuck and cannot continue with my build

**Comment by Pezzawinkle** [comment]
@stetown I tried looking into it, but could not find the issue specifically, I will have another look today, thanks for confirming that this is still an actual bug.

**Comment by stetown** [comment]
https://www.dropbox.com/s/u64mhf7955nzqlc/megabase%20new.zip?dl=0 

try that

**Comment by Pezzawinkle** [comment]
That is indeed an interesting interaction... ill see if i can force the platinum path open and push an update.

**Comment by stetown** [comment]
how long will it take for an update

**Comment by Pezzawinkle** [comment]
I have some good news... and some bad news.
If you start a new game (restart), the tech exists, but I don't know how to un-hide the techs in an active game.
I am investigating how to get the migration script to work correctly...

**Comment by stetown** [comment]
ok thanks

**Comment by stetown** [comment]
i have started a new save and they are there now

**Comment by Pezzawinkle** [comment]
i think i have a temp fix, the regular commands are not working though...
how do you feel about using commands?

**Comment by stetown** [comment]
ok but that will disable achivements

**Comment by Pezzawinkle** [comment]
i managed to get them into a migration script, enjoy the updated version now on the portal

**Comment by stetown** [comment]
nice
