### ISSUE TITLE
Wire route suggestions and Platinum smelting, casting questions

### ISSUE THREAD

**Issue by Andy91320** [Pezzawinkle/MadClowns#33]
Hello Pezzawinkle, I'm back again. 
      I'm back again. After updating the version of MadClown01's Processing-1.3.19 that you uploaded, the recipe for producing CPUs changed from requiring gold-plated copper wire to platinum-plated copper wire. May I suggest to change to gold-plated silver wire? This way the wire upgrade follows: copper wire - tinned copper wire - silver plated copper wire - gold plated copper wire - gold plated silver wire - gold alloy wire [made of gold, platinum, palladium (this metal does not appear in the mod yet)]. Platinum-plated copper wire does not seem to be used in reality.
       There is another problem just found: the whole platinum smelting, casting route is locked up can not be used. From the time I added your mod to the game, platinum ore has been left without a processing process and used only as a raw material for purple catalysts. I don't know if it has anything to do with angels, Bob's side.

**Comment by Pezzawinkle** [comment]
I would close this as a duplicate, but it has good details to help me fix the problem.

**Comment by Pezzawinkle** [comment]
The platinum wire issue should now be fixed, i will leave this open as a suggestion for palladium, as that has made me curious

**Comment by KiwiHawk** [comment]
> There is another problem just found: the whole platinum smelting route is locked up can not be used.

This should be fixed by #46
