### ISSUE TITLE
put this somewhere in data-updates to make clowns vanilla nuclear compatible with IR3

### ISSUE THREAD

**Issue by the-clorax** [Pezzawinkle/MadClowns#34]
data.raw.recipe["uranium-fuel-cell"].ingredients =
{
	{"lead-plate-special", 10},
	{"35%-uranium", 20},
}

	data.raw.recipe["mixed-oxide"].ingredients =
{
	{"lead-plate-special", 2},
	{"plutonium-239", 2},
	{"uranium-238", 2}
}
	data.raw.recipe["nuclear-fuel-reprocessing"].results =
{
    {name="plutonium-239", amount=1, probability=0.5},
    {name="uranium-238", amount=1},
	{name="lead-scrap", amount=2, probability=0.75},
	{name="steel-scrap", amount=5, probability=0.75}
}

**Comment by the-clorax** [comment]
do note it will need an "if mods[IndustrialRevolution] then"..."end" before it's put in a require function or in data-updates

**Comment by Pezzawinkle** [comment]
@the-clorax do you want these on top of the older IR updates, or just these?
