### ISSUE TITLE
Magnesium Research

### ISSUE THREAD

**Issue by Synessus** [Pezzawinkle/MadClowns#35]
Hello,

I currently play a game with a friend, AngelBob with MadClown. And we have a problem with the research.

We can not research Magnesium with all prerequisits researched.

		type = "technology",
		name = "advanced-magnesium-smelting",

		prerequisites = {"powder-metallurgy-1", "ore-processing-2"},

Even in game both prerequisites are green. I have no idea, why we cant line it in. (red background)
When i mouse-over it, it tells me that i am missing some prerequisites ..... no I don't.

I compared my local file with the online file here, both are the same. no differences. So I guess another mod fu##s it up.
I have no idea how to find out, what mod fu##s it up.

The link is the save of the start of the game. (we are curently 70h in. Don't want to upload the actual save without asking him first)

[https://drive.google.com/file/d/1Wxk0dntM5blLg9HBepIOUv7lq8ivd3uv/view?usp=share_link](url)

Why can we not research it? what mod breaks it? (btw, all mods updated. I found the problem 2 weeks ago.)
And btw, awsome mod ;)

kind regards,
Syn

**Comment by Pezzawinkle** [comment]
this looks like some kind of annoying migration error, I have tried loading that save, and the original tech exists in that save, but some others dont which are required)... if i restart the map, power metalurgy now starts at level 2, so i will have to fix that... but that should have been cleaned up on angels side. I will "try" to patch that now.

**Comment by Pezzawinkle** [comment]
This should not be fixed in the latest version, please let me know if it is still broken for you.
