### ISSUE TITLE
After latest update don't work with Angel

### ISSUE THREAD

**Issue by TierreAsh** [Pezzawinkle/MadClowns#36]
Get this error after recent update
![изображение](https://github.com/Pezzawinkle/MadClowns/assets/90751011/899be68d-542f-4acb-9bab-2e6e067df54f)

**Comment by dispod** [comment]
![Screenshot_1](https://github.com/Pezzawinkle/MadClowns/assets/28756052/23b9fbd0-8cc5-4a5b-8025-e58b410af786)

**Comment by dispod** [comment]
[factorio-current.log](https://github.com/Pezzawinkle/MadClowns/files/12144192/factorio-current.log)

**Comment by dispod** [comment]
it works (manual fix files)
Thank you

**Comment by Pezzawinkle** [comment]
My bad, should have done a little more testing before i pushed that last update out. Thanks for the patience.
