### ISSUE TITLE
Changes in Angel's Smelting making some research inaccessible

### ISSUE THREAD

**Issue by fangslash** [Pezzawinkle/MadClowns#38]
Hi, I'd like to report that some of the technologies in MadClown01's Processing is inaccessible.

At some point Angel's Smelting changed how their powder metallurgy technologies works. Specifically, "powder-metallurgy-1" was disabled by Angel's, so any tech with that as a dependency is no longer researchable. This includes Magnesium research mentioned in issue #35.

This bug is replicated with just MadClown01's Processing and Angel's Smelting. 

Cheers,
Fang

**Comment by Pezzawinkle** [comment]
This should not be fixed
