### ISSUE TITLE
"Automation science alt 1" not found at startup, Clown's Science and Angel's Refining need to be disabled

### ISSUE THREAD

**Issue by rainawareness** [Pezzawinkle/MadClowns#39]
![image](https://github.com/Pezzawinkle/MadClowns/assets/110186782/84a1a6cd-f150-43e5-b2b9-eb864cf48e4e)

**Comment by Pezzawinkle** [comment]
Thanks for the report, i am surprised it took someone that long to find it, i was missing a sanity check wrapper around that new function... ill get that fixed in a few mins, just checking the other issues first.
