### ISSUE TITLE
sodium-carbonate-omnide-salt does not exist

### ISSUE THREAD

**Issue by necrogami** [Pezzawinkle/MadClowns#4]
when trying to use your mods, i got this message error using this mod exactly:
failed to load mods: error in assignID: item with name 'sodium-carbonate-omnide-salt' does not exist
source: clows-ore9-crystall-salting (recipe)
mods to be disabled:
- clowns-extended-minerals 1.1.20

**Comment by Pezzawinkle** [comment]
This is known, and will be fixed in the next release (or if you get the current version from git)
Im actually waiting on an angels update as i have been keeping the live branch of this up-to-date with angels dev branch, and it is likely to break if i publish this as is.
