### ISSUE TITLE
Processing has stopped working with Angels

### ISSUE THREAD

**Issue by TsumiHokiro** [Pezzawinkle/MadClowns#42]
Madclowns's Processing has stopped working after latest update of Angel's Refining, Smelting and Petrochemical Processing (Updated 23/12/22).
![Processing 1-Factorio 1 1 100](https://github.com/Pezzawinkle/MadClowns/assets/4119532/09bada23-34b1-4f0c-bfdb-801185784568)

**Comment by AssasinAsha** [comment]
One of the research prototypes needs updating in Clown's Processing.
[Here](https://github.com/Arch666Angel/mods/issues/956) is the issue on Angel's GitHub that I responded to with a possible fix (depending on where the tech should go).

I still say it's really strange that Processing doesn't show in the error list. But, what do I know? I'm not a modder or anything ;).

**Comment by Pezzawinkle** [comment]
The newly posted version should fix this, sorry for the delay
