### ISSUE TITLE
Recipe Hiding

### ISSUE THREAD

**Issue by adoa** [Pezzawinkle/MadClowns#5]
After looking at Angel's, I also looked at the current master branch of MadClown's and still see the following recipes that might need to be hidden (all of Angel+Bob+Clown, default settings):

- `casting-powder-depleted-uranium-3`, `casting-powder-depleted-uranium-4`
- `algae-violet`, `algae-orange`, `methylmercury-algae`
- `thorium-nuclear-fuel-reprocessing`, `advanced-nuclear-fuel-reprocessing`, `mixed-oxide`, `thorium-mixed-oxide`

**Comment by Pezzawinkle** [comment]
I'm not sure if I have fixed this already (I tend to multi-patch), when I updated angels ones...
I will take a closer look at these before the next release.

**Comment by Pezzawinkle** [comment]
Casting powders have been activated...
Algae to methylmercury has been added to a tech to unlock... orange removed
I was having a hard time with the nuclear rebalance with angelsindustries and clowns, so I have left these in for now, if anything they are a little short-cut vs the regular version.
@adoa let me know if you still want me to remove these, to just leave the industries versions?
