### ISSUE TITLE
Move items to Equipment tab

### ISSUE THREAD

**Issue by KiwiHawk** [Pezzawinkle/MadClowns#6]
Base Game:
- Belt immunity equipment

Bobs:
- Personal roboport area expander
- Personal roboport area expander 2
- Personal roboport area expander 3
- Personal roboport area expander 4
- Personal roboport chargepad
- Personal roboport chargepad 2
- Personal roboport chargepad 3
- Personal roboport chargepad 4
- Personal roboport control
- Personal roboport control 2
- Personal roboport control 3
- Personal roboport control 4
- Personal roboport MK3
- Personal roboport MK4

**Comment by Pezzawinkle** [comment]
I believe this was fixed on angels side a few patches ago, and most of the re-grouping functions that clowns did are now gone from this code-base.
