### ISSUE TITLE
Recipe not work

### ISSUE THREAD

**Issue by KeiranGreen** [Pezzawinkle/MadClowns#8]
Hello! After udating MadClown01's Extended AngelBob Minerals to the lastest version, recepies are missing from mashines

Ore Crusher no longer crush mad's ores

To crush ore now you need a Ore Sorting instead of Ore crusher
![Image](https://i.imgur.com/IEZddjm.jpg)

No mashine need to produce Chunk
![Image](https://i.imgur.com/H4zfe6V.jpg)

Maybe other errors have been founded...

Mod List: https://pastebin.com/Yp8CQHyK

**Comment by Pezzawinkle** [comment]
Ill take another look at it when I get home, was a bit rushed, sorry

**Comment by Pezzawinkle** [comment]
released on the mod portal

**Comment by KeiranGreen** [comment]
Thanks!
